spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test44?useUnicode=yes&characterEncoding=utf-8&useSSL=true
    username: root
    password: root
  session:
    store-type: none
  mvc:
    static-path-pattern: /**
#  security:
#    user:
#      password: 123456
#      name: fulinhu

#       basic:
#                # 打开/关闭spring security 打开默认的用户名为user，密码是程序启动时输出的
#                  enabled: false
##  oauth2:
##    client:
##      client-id: gwf
##      client-secret: mySecret
#
server:
  port: 9090
  servlet:
    session:
      timeout:
        timeout: 600



#
#
#gwf:
#  security:
#    browser:
#      loginPage: /demo-signIn.html
#      loginType: JSON
#      signUpUrl: /demo-signUp.html
#      signOutUrl: /demo-logout.html
#    social:
#      qq:
#        app-id: 101447248
#        app-secret: c6e5d368dc5e71061f568a04488b5726
#        providerId: qq
#      filterProcessesUrl : /auth
#      weixin:
#        app-id: wxd99431bbff8305a0
#        app-secret: 60f78681d063590a469f1b297feff3c4
#        providerId: weixin
#    oauth2:
#      clients[0]:
#        clientId: gwf
#        clientSecret: mySecret
#        accessTokenValidateSeconds: 3600
#      clients[1]:
#        clientId: jd
#        clientSecret: mySecret
#        accessTokenValidateSeconds: 4200
#      storeType: jwt
#      jwtSigningKey: gwf
##    code:
##      image:
##        width: 100  # 宽高可从浏览器获取
##        heigth: 100
##        length: 4
##        url: /user,/user/*
##        expireIn: 160
##      sms:
##        length: 6
##        url: /user,/user/*
##        expireIn: 160



#自定义属性
flh1:
  scurity:
    browser:
      signUpUrl: /demo-signUp11.html