spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test44?useUnicode=yes&characterEncoding=utf-8&useSSL=true
    username: root
    password: root



